#!/bin/bash

OUTPUT=config.mk
SUPPORTED_TARGETS="x86_64 aarch64"
SUPPORTED_OPTLEVELS="0 1 2 3"
BUTILS_SUFFIXES="Darwin:-elf- Linux:-linux-gnu-"

print_help() {
	echo Usage: configure.sh [options]
	echo Options:
	echo "	-h | --help (print this message)"
	echo "	-t <TARGET> (supported: $SUPPORTED_TARGETS)"
	echo "	-o <OPTIMIZATION LEVEL> (supported: $SUPPORTED_OPTLEVELS)"
	echo "	-p <BINUTILS PREFIX>"
	exit $1
}

contains() {
	for word in $1;	do
		[[ $word = $2 ]] && return 0
	done
	return 1
}

aarr_index() {
	for pair in $1; do
		[ "${pair%%:*}" = $2 ] && echo "${pair##*:}" && return
	done
}

add_var() {
	echo "$1 = $2"
	echo "$1 = $2" >> $OUTPUT
}

target=$(uname -m)
optlevel=3

for ((i = 1; i <= $#; i++)); do
	if [[ ${!i} = "-h" || ${!i} = "--help" ]]; then print_help 0; fi
	if [ ${!i} = "-t" ]; then target=${@:i+1:1}; ((i++)); continue; fi
	if [ ${!i} = "-o" ]; then optlevel=${@:i+1:1}; ((i++)); continue; fi
	if [ ${!i} = "-p" ]; then buprefix=${@:i+1:1}; ((i++)); continue; fi
	print_help 1
done

if ! contains "$SUPPORTED_TARGETS" "$target"; then
	echo "unsupported target (supported: $SUPPORTED_TARGETS)"
	exit 1
fi
if ! contains "$SUPPORTED_OPTLEVELS" "$optlevel"; then
	echo "invalid optimization level (supported: $SUPPORTED_OPTLEVELS)"
	exit 1
fi
if [ -z "$buprefix" ]; then
	buprefix=$target$(aarr_index "$BUTILS_SUFFIXES" `uname`)
fi

echo "# generated by configure.sh, do not modify" > $OUTPUT

add_var TARGET $target
add_var OPTLEVEL $optlevel
add_var BUPREFIX $buprefix
